use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, PartialEq)]
#[repr(u32)]
pub enum ScoutAccessError {
    AlreadyInitialized = 1,
    NotInitialized = 2,
    ContractPaused = 3,
    Unauthorized = 4,
    InsufficientFee = 5,
    ScoutNotSubscribed = 6,
    SubscriptionExpired = 7,
    AlreadyContacted = 8,
    InvalidTier = 9,
    Overflow = 10,
    TrialOfferNotFound = 11,
    PlayerNotRegistered = 12,
    ScoutNotRegistered = 13,
    PlayerCapReached = 14,
    SubscriptionNotFound = 15,
    ContactRecordNotFound = 16,
    TrialOfferExpired = 17,
    InvalidSubscriptionDuration = 18,
    FeeConfigNotFound = 19,
    TokenTransferFailed = 20,
    InvalidContactFee = 21,
    InvalidSubFee = 22,
    EliteOnlyFeature = 23,
    MigrationAlreadyComplete = 24,
    MigrationNotFound = 25,
    InvalidMigrationVersion = 26,
    MigrationDataCorrupted = 27,
    MigrationStateMismatch = 28,
    MigrationNotActive = 29,
    MigrationReplayDetected = 30,
    MigrationConflict = 31,
    MigrationVersionMismatch = 32,
    MigrationChecksumFailed = 33,
    MigrationRollbackFailed = 34,
    SubscriptionRecordEvicted = 35,
    PayToContactPaused = 36,
    TrialEscrowNotOutstanding = 37,
}
